### ISSUE TITLE
Error with Main.java class

### ISSUE THREAD

**Issue by DilankaPradeep** [Copyleaks/Java-Plagiarism-Checker#1]
Error out put is "Missing argument: "email"." , Project is not run

**Comment by YehonatanB** [comment]
Hi, 
Which running arguments are you using in order to run the application?

It's seems like you forgot to specify the "-e" argument.

Try to use this arguments (modify according to your personal information):
`--e "Your@email.com" --k "Your API key GUID" --url "http://example.co.il/page/to/scan"`

Still have problems?

**Comment by DilankaPradeep** [comment]
can you send me java code that need to add my email address and APIKEY_KEY?

On Sun, May 29, 2016 at 4:46 PM, Copyleaks notifications@github.com wrote:

> Hi,
> Which running arguments do you using in order to run the application?
> 
> It's seems that you forgot to specify the "-e" argument.
> 
> Try to use this arguments (modify according to your personal information:
> --e "Your@email.com" --k "Your API key GUID" --url "
> http://example.co.il/page/to/scan"
> 
> Still have problems?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Copyleaks/Java-Plagiarism-Checker/issues/1#issuecomment-222355337,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALqDH3YjcsorHG3UiK6D-146rMujmBF4ks5qGXWcgaJpZM4IpQxT
> .

## 

Dilanka Pradeep

**Comment by YehonatanB** [comment]
Hi, 
You have two options to run the code:
1) Before running the code, compile it in your computer. This code already includes "Main()" function which contains an example for how to use it from the command line (with program arguments). After building the executable file, run it with the arguments I specified above (last comment).

Did you manage to build the code? If not, use those instructions:
https://github.com/Copyleaks/Java-Plagiarism-Checker#configuration

2) Another option is to add this library to your existing Java project and use it from there. In order do it, you need to fork this repository to your machine and export it as JAR file. You can use this JAR file in your existing project by referencing to it.

Which option is best for you?

**Comment by DilankaPradeep** [comment]
Yes,Eclipse installed in my computer. I follow the steps given in
configuration.
Then I run the Main.java in default package. Then it gives error as
"Missing argument: "email"."
Then I going with sign up process and get my api key from API Dashboard.

But still I got confuse where should I enter my email address and API key.
Can you please tell me which line in which java program that I need to add
those informations to run this Main.java program?

Thank you!!!

On Sun, May 29, 2016 at 5:02 PM, Copyleaks notifications@github.com wrote:

> Hi,
> Before running the code, you need to compile it in your computer. After
> building the executable file, you can run it with the arguments I specified
> above (last comment).
> 
> Did you success to build the code? If not, use those instructions:
> https://github.com/Copyleaks/Java-Plagiarism-Checker#configuration
> 
> Do you have Eclipse installed in your computer?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Copyleaks/Java-Plagiarism-Checker/issues/1#issuecomment-222355917,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALqDHz2L4L-IsXe5D78lkEtvYGmlRoxHks5qGXlJgaJpZM4IpQxT
> .

## 

Dilanka Pradeep

**Comment by YehonatanB** [comment]
I understand. 

So, the information you have to add is this (as we said in the previous message):
`--e "Your@email.com" --k "Your API key GUID" --url "http://example.co.il/page/to/scan"`

Now:
1. Copy this arguments
2. Go to Eclipse
3. Click on "Run" (menu item) -> "Debug configuration...".
4. Create a new debug profile for your application. It should looks like this - steps are highlighted in yellow:
   ![debug-configurations-main](https://cloud.githubusercontent.com/assets/11980663/15633072/ead1479c-25ac-11e6-9678-f8de57388989.jpg)
   ![debug configurations-arguments](https://cloud.githubusercontent.com/assets/11980663/15633073/ec139ac4-25ac-11e6-8b9f-828e8ebcec67.jpg)

**Comment by DilankaPradeep** [comment]
It's work now, but it provide

Login to Copyleaks cloud...Done!
Checking account balance...Done (3 credits)!
Failed!
**\* Error (5):
Failed to download the requested url

I use your url as it is. what is the URL that I need to use?
How can I use Local document insted of URL?

On Sun, May 29, 2016 at 5:23 PM, Copyleaks notifications@github.com wrote:

> I'm understand.
> 
> So, the information you have to add is this (as we said in the previous
> message):
> --e "Your@email.com" --k "Your API key GUID" --url "
> http://example.co.il/page/to/scan"
> 
> Now:
> 1. Copy this arguments
> 2. Go to Eclipse
> 3. Click on "Run" (menu item) -> "Debug configuration...".
> 4. Create a new debug profile for your application. it should looks
>    like this - steps are highlighted with yellow: [image:
>    debug-configurations-main]
>    https://cloud.githubusercontent.com/assets/11980663/15633072/ead1479c-25ac-11e6-9678-f8de57388989.jpg [image:
>    debug configurations-arguments]
>    https://cloud.githubusercontent.com/assets/11980663/15633073/ec139ac4-25ac-11e6-8b9f-828e8ebcec67.jpg
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Copyleaks/Java-Plagiarism-Checker/issues/1#issuecomment-222356669,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALqDH2XnZ4LnPlwHW4lHgTn5nJsBVdGZks5qGX4zgaJpZM4IpQxT
> .

## 

Dilanka Pradeep

**Comment by YehonatanB** [comment]
OK. That is good news. 

With this SDK you can scan any valid URL (URL that returns HTTP code 200 - success).

for example, change the URL to "http://example.com" and it should be fine. 
However, we recommend you:
1. Work in Sandbox mode. This done by **un**commenting this code (from Main.java):
`scanOptions.setSandboxMode(true);`
Using sandbox mode will allow you to test the API as much as you want with no costs. This is good for the integration stage.
2. Scan the content you wish to search. It can be content that hosted in a website (html\txt files) or upload files (such as pdf\doc\docx...).

**Comment by DilankaPradeep** [comment]
Is there any GUI prompt to provide local doc (such as pdf\doc\docx...) to
upload and check plagiarism ? How to check plagiarism by using the program?

On Sun, May 29, 2016 at 5:44 PM, Copyleaks notifications@github.com wrote:

> OK. This is good news.
> 
> With this SDK you can scan any valid URL (valid URL is when the URL return
> HTTP code 200 - success).
> 
> for example, change this URL to "http://example.com" and this should be
> fine.
> However, we recommend you:
> 1. Work on Sandbox mode. This done by _un_commenting this code (from
> Main.java):
> scanOptions.setSandboxMode(true);
> This code line making the search in playground and won't cost you credits.
> This is good for integration stage.
> 2. Scan the content you wish to search. This can be content that hosted in
> website (html\txt files) or upload files (such as pdf\doc\docx...).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Copyleaks/Java-Plagiarism-Checker/issues/1#issuecomment-222357443,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALqDH4cPa5aqWxivsleGR4sjlvy_hQi5ks5qGYMLgaJpZM4IpQxT
> .

## 

Dilanka Pradeep

**Comment by YehonatanB** [comment]
Copyleaks SDKs doesn't include GUI to scan files. The SDKs are built for integrating with automated systems. 

In order to scan a file, you need to specify its path. For example:
`--e "Your@email.com" --k "Your API key GUID" --f "C:\directory\yourfile.pdf"`

If you are looking for GUI, you need to use our website ([Copyleaks plagiarism checker](https://copyleaks.com)). In the next few weeks you will have full GUI that will allow uploading files manually.

**Comment by DilankaPradeep** [comment]
I use --f "C:\Users\Dilanka\Desktop\RIDE97.pdf" to input pdf. But output
comes with error - Unable to parse input arguments. Please try agian or
USER "--help" for more information.

On Sun, May 29, 2016 at 6:15 PM, Dilanka Gunarathna dilanka13627@gmail.com
wrote:

> Is there any GUI prompt to provide local doc (such as pdf\doc\docx...) to
> upload and check plagiarism ? How to check plagiarism by using the
> program?
> 
> On Sun, May 29, 2016 at 5:44 PM, Copyleaks notifications@github.com
> wrote:
> 
> > OK. This is good news.
> > 
> > With this SDK you can scan any valid URL (valid URL is when the URL
> > return HTTP code 200 - success).
> > 
> > for example, change this URL to "http://example.com" and this should be
> > fine.
> > However, we recommend you:
> > 1. Work on Sandbox mode. This done by _un_commenting this code (from
> > Main.java):
> > scanOptions.setSandboxMode(true);
> > This code line making the search in playground and won't cost you
> > credits. This is good for integration stage.
> > 2. Scan the content you wish to search. This can be content that hosted
> > in website (html\txt files) or upload files (such as pdf\doc\docx...).
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/Copyleaks/Java-Plagiarism-Checker/issues/1#issuecomment-222357443,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ALqDH4cPa5aqWxivsleGR4sjlvy_hQi5ks5qGYMLgaJpZM4IpQxT
> > .
> 
> ## 
> 
> Dilanka Pradeep

## 

Dilanka Pradeep

**Comment by YehonatanB** [comment]
Sorry, my mistake. It should be "-f" (instead of "--f"). So, try:
`-f "C:\Users\Dilanka\Desktop\RIDE97.pdf"`

**Comment by DilankaPradeep** [comment]
Thanks, it's work...!!!!

It's given out put like this

Scanning...

|==============================                    | 61%
|==================================================| 100%

Result 1:
Url: http://example.com/sandbox-4a24fe83-6c08-4142-8b22-252dee6ac32f
Percents: 90
CopiedWords: 257

Result 2:
Url: http://example.com/sandbox-5cf9bf90-efba-496b-8afc-d41d96e28db6
Percents: 90
CopiedWords: 257

what is 61%??
All url based with example.com/sandbox... what is that?
Can't we get real Url for them?

On Sun, May 29, 2016 at 8:08 PM, Copyleaks notifications@github.com wrote:

> Sorry, my mistake. It's should be "-f" (instead of "--f"). So, try it like
> this:
> -f "C:\Users\Dilanka\Desktop\RIDE97.pdf"
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Copyleaks/Java-Plagiarism-Checker/issues/1#issuecomment-222364030,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALqDH6k4-xOcSeytTXFNHww0i07R2o1Iks5qGaThgaJpZM4IpQxT
> .

## 

Dilanka Pradeep

**Comment by YehonatanB** [comment]
OK, you are on the right track. 

This:
`|==============================                                          | 61% |==================================================| 100%`
shows the progress of the scan. When it reaches 100%, the scan has completed and you are ready to get the results.

The "http://example.com/sandbox-..." URLs are for sandbox mode. It does not cost you credits and is great for testing purposes. When you are ready for production, just delete this line (in Main.java file):
`scanOptions.setSandboxMode(true);`
After, build the program again and scan and get real results.
